name       : mono
version    : 4.0.2.5
release    : 4 
source     :
    - http://download.mono-project.com/sources/mono/mono-4.0.2.5.tar.bz2 : b074584eea5bbaaf29362486a69d70abe53d0d2feb334f231fa9c841cf6fd651
license    : GPL-2.0 
summary    : Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
description: |
    Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
libsplit   : no
setup      : |
    NOCONFIGURE=1 ./autogen.sh --prefix=/usr
    %configure 
build      : |
    %make get-monolite-latest
    %make
install    : |
    %make_install
    rm %installroot%/%libdir%/*.la
