name       : mono
version    : 5.4.1.6
release    : 15
source     :
    - https://download.mono-project.com/sources/mono/mono-5.4.1.6.tar.bz2 : bdfda0fe9ad5ce20bb2cf9e9bf28fed40f324141297479824e1f65d97da565df
license    : GPL-2.0
component  : programming
summary    : Mono is an open source implementation of Microsoft's .NET Framework.
description: |
    Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
patterns   :
    - /usr/lib64/libMono*.so
    - /usr/lib64/libikvm*.so
setup      : |
    %configure \
        --disable-quiet-build \
        --disable-system-aot \
        --enable-parallel-mark \
        --with-mcs-docs=no
build      : |
    %make
    # Build Jay
    cd mcs/jay
    %make
install    : |
    %make_install
    # Install Jay
    cd mcs/jay
    %make_install
    # Install binfmt conf file
    install -Dm644 $pkgfiles/mono.binfmt.d $installdir/usr/lib/binfmt.d/mono.conf
