name       : mono
version    : 6.12.0.122
release    : 23
source     :
    - https://download.mono-project.com/sources/mono/mono-6.12.0.122.tar.xz : 29c277660fc5e7513107aee1cbf8c5057c9370a4cdfeda2fc781be6986d89d23
license    :
    - BSD-3-Clause
    - MIT
component  : programming
summary    : Mono is an open source implementation of Microsoft's .NET Framework
description: |
    Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
patterns   :
    - /usr/lib64/libMono*.so
    - /usr/lib64/libmono*.so
rundeps    :
    - libgdiplus
setup      : |
    %configure \
        --disable-quiet-build \
        --disable-system-aot \
        --enable-ninja \
        --enable-parallel-mark \
        --with-ikvm-native=no \
        --with-mcs-docs=no \
        --with-xen-opt=no
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/mono.binfmt.d $installdir/usr/lib/binfmt.d/mono.conf
