name       : mono
version    : 4.2.1.102
release    : 6
source     :
    - http://download.mono-project.com/sources/mono/mono-4.2.1.102.tar.bz2 : b7b461fe04375f621d88166ba8c6f1cb33c439fd3e17136460f7d087a51ed792
license    : GPL-2.0 
summary    : Mono is an open source implementation of Microsoft's .NET Framework.
description: |
    Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
setup      : |
    %configure \
        --disable-quiet-build \
        --disable-system-aot \
        --with-mcs-docs=no
build      : |
    %make
    # Build Jay
    cd $srcdir/mcs/jay
    %make
install    : |
    %make_install
    # Install Jay
    cd $srcdir/mcs/jay
    %make_install
    # Install binfmt conf file
    install -Dm644 $pkgfiles/mono.binfmt.d $installdir/usr/lib/binfmt.d/mono.conf
    rm -rf $installdir/%libdir%/*.la
