name       : mono
version    : 4.6.2.7
release    : 10
source     :
    - https://download.mono-project.com/sources/mono/mono-4.6.2.7.tar.bz2 : b69ead7db7590277630685f3fcad84a5ac2f83e40563f0dc8cf139b10cbe6b31
license    : GPL-2.0
component  : programming
summary    : Mono is an open source implementation of Microsoft's .NET Framework.
description: |
    Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
setup      : |
    %configure \
        --disable-quiet-build \
        --disable-system-aot \
        --with-mcs-docs=no
build      : |
    %make
    # Build Jay
    cd mcs/jay
    %make
install    : |
    %make_install
    # Install Jay
    cd mcs/jay
    %make_install
    # Install binfmt conf file
    install -Dm644 $pkgfiles/mono.binfmt.d $installdir/usr/lib/binfmt.d/mono.conf
