name       : mono
version    : 4.8.1.0
release    : 12
source     :
    - https://download.mono-project.com/sources/mono/mono-4.8.1.0.tar.bz2 : 18cb38a670e51609c36c687ed90ad42cfedabeffd0a2dc5f7f0c46249eb8dbef
license    : GPL-2.0
component  : programming
summary    : Mono is an open source implementation of Microsoft's .NET Framework.
description: |
    Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
patterns   :
    - /usr/lib64/libMono*.so
    - /usr/lib64/libikvm*.so
setup      : |
    %configure \
        --disable-quiet-build \
        --disable-system-aot \
        --with-mcs-docs=no
build      : |
    %make
    # Build Jay
    cd mcs/jay
    %make
install    : |
    %make_install
    # Install Jay
    cd mcs/jay
    %make_install
    # Install binfmt conf file
    install -Dm644 $pkgfiles/mono.binfmt.d $installdir/usr/lib/binfmt.d/mono.conf
