name       : mono
version    : 5.0.0.100
release    : 13
source     :
    - https://download.mono-project.com/sources/mono/mono-5.0.0.100.tar.bz2 : 368da3ff9f42592920cd8cf6fa15c6c16558e967144c4d3df873352e5d2bb6df
license    : GPL-2.0
component  : programming
summary    : Mono is an open source implementation of Microsoft's .NET Framework.
description: |
    Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
patterns   :
    - /usr/lib64/libMono*.so
    - /usr/lib64/libikvm*.so
setup      : |
    %configure \
        --disable-quiet-build \
        --disable-system-aot \
        --enable-parallel-mark \
        --with-mcs-docs=no
build      : |
    %make
    # Build Jay
    cd mcs/jay
    %make
install    : |
    %make_install
    # Install Jay
    cd mcs/jay
    %make_install
    # Install binfmt conf file
    install -Dm644 $pkgfiles/mono.binfmt.d $installdir/usr/lib/binfmt.d/mono.conf
