name       : mono
version    : 4.2.3.4
release    : 9
source     :
    - http://download.mono-project.com/sources/mono/mono-4.2.3.4.tar.bz2 : 4703d390416a6e9977585f13711f59a6d54431086c2dbacee49888dcc31937be
license    : GPL-2.0 
summary    : Mono is an open source implementation of Microsoft's .NET Framework.
description: |
    Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
setup      : |
    sed -i -e "s:/2.0/:/4.5/:g" $srcdir/data/mono-nunit.pc.in
    %configure \
        --disable-quiet-build \
        --disable-system-aot \
        --with-mcs-docs=no
build      : |
    %make
    # Build Jay
    cd $srcdir/mcs/jay
    %make
install    : |
    %make_install
    # Install Jay
    cd $srcdir/mcs/jay
    %make_install
    # Install binfmt conf file
    install -Dm644 $pkgfiles/mono.binfmt.d $installdir/usr/lib/binfmt.d/mono.conf
    rm -rf $installdir/%libdir%/*.la
