name       : mono
version    : 3.12.1
release    : 4 
source     :
    - http://download.mono-project.com/sources/mono/mono-3.12.1.tar.bz2 : 5d8cf153af2948c06bc9fbf5088f6834868e4db8e5f41c7cff76da173732b60d
license    : GPL-2.0 
summary    : Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
description: |
    Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
libsplit   : no
setup      : |
    %configure 
build      : |
    %make
install    : |
    %make_install
    rm %installroot%/%libdir%/*.la
