name       : mono
version    : 4.2.2.30
release    : 7
source     :
    - http://download.mono-project.com/sources/mono/mono-4.2.2.30.tar.bz2 : 57858cd033be9915d7abdc5158c1faae8fa05757c3b7117cab3d703aa696c56b
license    : GPL-2.0 
summary    : Mono is an open source implementation of Microsoft's .NET Framework.
description: |
    Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
setup      : |
    %configure \
        --disable-quiet-build \
        --disable-system-aot \
        --with-mcs-docs=no
build      : |
    %make
    # Build Jay
    cd $srcdir/mcs/jay
    %make
install    : |
    %make_install
    # Install Jay
    cd $srcdir/mcs/jay
    %make_install
    # Install binfmt conf file
    install -Dm644 $pkgfiles/mono.binfmt.d $installdir/usr/lib/binfmt.d/mono.conf
    rm -rf $installdir/%libdir%/*.la
