name       : mono
version    : 4.0.3.13
release    : 3
source     :
    - http://download.mono-project.com/sources/mono/mono-4.0.3.13.tar.bz2 : ce3a1021844f0c13ac970a014aad4ed9d331ac180d0d6ef541f0fd48699725a6
license    : GPL-2.0 
summary    : Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
description: |
    Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
libsplit   : no
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm %installroot%/%libdir%/*.la
