name       : mono
version    : 6.0.0.327
release    : 18
source     :
    - https://download.mono-project.com/sources/mono/mono-6.0.0.327.tar.xz : f51184ce4b90c93fc2bf5ca02775dd2a1ea023e056089d286ea72f1c68586442
license    :
    - BSD-3-Clause
    - MIT
component  : programming
summary    : Mono is an open source implementation of Microsoft's .NET Framework
description: |
    Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
patterns   :
    - /usr/lib64/libMono*.so
    - /usr/lib64/libmono*.so
rundeps  :
    - libgdiplus
setup      : |
    %configure \
        --disable-quiet-build \
        --disable-system-aot \
        --enable-ninja \
        --enable-parallel-mark \
        --with-ikvm-native=no \
        --with-mcs-docs=no \
        --with-xen-opt=no
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/mono.binfmt.d $installdir/usr/lib/binfmt.d/mono.conf
