name       : mono
version    : 5.14.0.177
release    : 17
source     :
    - https://download.mono-project.com/sources/mono/mono-5.14.0.177.tar.bz2 : d4f5fa2e8188d66fbc8054f4145711e45c1faa6d070e63600efab93d1d189498
license    :
    - BSD-3-Clause
    - MIT
component  : programming
summary    : Mono is an open source implementation of Microsoft's .NET Framework
description: |
    Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
patterns   :
    - /usr/lib64/libMono*.so
    - /usr/lib64/libikvm*.so
setup      : |
    %configure \
        --disable-quiet-build \
        --disable-system-aot \
        --enable-parallel-mark \
        --with-mcs-docs=no
build      : |
    %make
    # Build Jay
    %make -C mcs/jay
install    : |
    %make_install
    # Install Jay
    %make_install -C mcs/jay
    # Install binfmt conf file

    install -Dm00644 $pkgfiles/mono.binfmt.d $installdir/usr/lib/binfmt.d/mono.conf
